twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locales: '%locales%'
        pos_color: ''
        neg_color: ''
        card_height: '%card_height%'
