insert into plateforme values(1,NULL,'RetroCI','','ABIDJAN');
insert into plateforme values(2,NULL,'IPCI','','ADIOPODOUME');
insert into plateforme values(3,NULL,'CHU YOPOUGON','','ABIDJAN');
insert into plateforme values(4,NULL,'CEPREF','','ABIDJAN');
insert into plateforme values(5,NULL,'INSP','','ABIDJAN');
insert into plateforme values(6,NULL,'CEDRES','','ABIDJAN');
insert into plateforme values(7,NULL,'CHR YAMOUSSOUKRO','','YAMOUSSOUKRO');
insert into plateforme values(8,NULL,'CHR ABENGOUROU','','ABENGOUROU');
insert into plateforme values(9,NULL,'CHU BOUAKE','','BOUAKE');
insert into plateforme values(10,NULL,'CHR KORHOGO','','KORHOGO');
insert into plateforme values(11,NULL,'HG GAGNOA','','GAGNOA');
insert into plateforme values(12,NULL,'HG ABOBO SUD','','ABIDJAN');
insert into plateforme values(13,NULL,'HG SOUBRE','','SOUBRE');
insert into plateforme values(14,NULL,'CHR MAN','','MAN');
insert into plateforme values(15,NULL,'CHR SAN PEDRO','','SAN-PEDRO');
insert into plateforme values(16,NULL,'CIRBA','','ABIDJAN');
insert into plateforme values(17,NULL,'CHR GAGNOA','','GAGNOA');
